// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWEO9t9Hr12SRIqrwiBP5DXfmltxdtLFY',
    appId: '1:864537708063:web:689bba45ccbd477ec5b72a',
    messagingSenderId: '864537708063',
    projectId: 'student-directory-app-ec09b',
    authDomain: 'student-directory-app-ec09b.firebaseapp.com',
    storageBucket: 'student-directory-app-ec09b.firebasestorage.app',
    measurementId: 'G-7E7KYPN3P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwlzH1tDL9abMSGMa19HV4fomlsHZyrUY',
    appId: '1:864537708063:android:c63b6f2c7e30e5c8c5b72a',
    messagingSenderId: '864537708063',
    projectId: 'student-directory-app-ec09b',
    storageBucket: 'student-directory-app-ec09b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHPuCsMwNOz5JoAkz8pRNRd4iNd9XutCM',
    appId: '1:864537708063:ios:0ba109a7a4c80fedc5b72a',
    messagingSenderId: '864537708063',
    projectId: 'student-directory-app-ec09b',
    storageBucket: 'student-directory-app-ec09b.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHPuCsMwNOz5JoAkz8pRNRd4iNd9XutCM',
    appId: '1:864537708063:ios:0ba109a7a4c80fedc5b72a',
    messagingSenderId: '864537708063',
    projectId: 'student-directory-app-ec09b',
    storageBucket: 'student-directory-app-ec09b.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectoryAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWEO9t9Hr12SRIqrwiBP5DXfmltxdtLFY',
    appId: '1:864537708063:web:bc4fbea3dd9fcf9cc5b72a',
    messagingSenderId: '864537708063',
    projectId: 'student-directory-app-ec09b',
    authDomain: 'student-directory-app-ec09b.firebaseapp.com',
    storageBucket: 'student-directory-app-ec09b.firebasestorage.app',
    measurementId: 'G-6XZLRFRWNM',
  );
}
